version: '3'

services:
# PHP - FPM
   php-fpm:
      build: ./docker_file/php-fpm
      volumes:
         - ./src/wordpress:/var/www/html

# NGINX
   web:
      depends_on:
         - php-fpm
         - wordpress

      build: ./docker_file/nginx
      restart: always
      ports:
         - "6001:80"
      volumes:
         - ./src/wordpress:/var/www/html
         - ./docker_file/nginx/configs/nginx.conf:/etc/nginx/nginx.conf
         - ./docker_file/nginx/configs/sites-available/:/etc/nginx/sites-available
         - ./src/logs/nginx:/var/log/nginx

# Database
   db:
      build: ./docker_file/mariadb
      restart: always

      environment:
         MYSQL_ROOT_PASSWORD: 123
         MYSQL_DATABASE: wordpress
         MYSQL_USER:     wordpress
         MYSQL_PASSWORD: wordpress
      volumes:
         - ./src/db/data:/var/lib/mysql

# wordpress
   wordpress:
      depends_on:
         - db

      build: ./docker_file/wordpress
      ports:
         - "6003:80"
      restart: always

      environment:
         WORDPRESS_DB_HOST:     db
         WORDPRESS_DB_NAME:     wordpress
         WORDPRESS_DB_USER:     wordpress
         WORDPRESS_DB_PASSWORD: wordpress
      volumes:
         - ./src/wordpress:/var/www/html

# phpmyadmin
   phpmyadmin:
      depends_on: 
         - db

      build: ./docker_file/phpmyadmin
      restart: always
      ports:
         - "6002:80"

      environment:
         MYSQL_ROOT_PASSWORD: 123
